BigHouzzz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('users.urls')),
    path('profile/', views.profile, name='profile'),
    path('cars/', include('cars.urls')),
    path('house/', include('flats.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:  # Если запущен режим отладки, то
    # Добавить пути для статических файлов STATIC и MEDIA
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # Включить инструмент отладки Django Debug Toolbar
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.csrf_failure'

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('<int:car_id>/', views.car_detail, name='car_detail'),
    path('', views.cars_index, name='cars_index'),
]

core/urls.py
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('about/', views.AboutProjectView.as_view(), name='about'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
]

templates/includes/footer.html
{# Footer #}
<footer>
    <div class="container align-items-center bg-dark rounded text-white-50 p-3 my-3 ">
        <div class="row">
            <div class="text-center mt-auto">
                &copy; BigHouzzz, 2023-{% now 'Y' %}.
            </div>
        </div>
    </div>
</footer>

templates/includes/header.html
{# Header #}
<header>
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark mb-4">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'core:index' %}">
                        <i class="bi bi-buildings" style="font-size: 32; width: 2rem; height: 2rem"></i>
                        BigHouzzz
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
<!--                            <li class="nav-item">
                                <a class="nav-link
                                    {% if request.resolver_match.view_name  == 'cars:cars_index' %}active{% endif %}"
                                   href="{% url 'cars:cars_index' %}">Квартиры</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link
                                    {% if request.resolver_match.view_name  == 'cars:cars_index' %}active{% endif %}"
                                   href="{% url 'cars:cars_index' %}">Дома</a>
                            </li>-->
                            <li class="nav-item">
                                <a class="nav-link
                                    {% if request.resolver_match.view_name  == 'cars:cars_index' %}active{% endif %}"
                                   href="{% url 'cars:cars_index' %}">Транспорт</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link
                                    {% if request.resolver_match.view_name  == 'core:about' %}active{% endif %}"
                                   href="{% url 'core:about' %}">О проекте</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link
                                    {% if request.resolver_match.view_name  == 'core:contacts' %}active{% endif %}"
                                   href="{% url 'core:contacts' %}">Контакты</a>
                            </li>
                        </ul>
                        <div class="text-end">
                            {% if user.is_authenticated %}
                                <div class="dropdown">
                                    <a class="btn btn-outline-light me-md-2 dropdown-toggle" role="button" id="dropdownUserMenuButton" data-bs-toggle="dropdown" aria-expanded="false">Пользователь: {{ user.username }}</a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownUserMenuButton">
                                        <li><a class="dropdown-item" href="{% url 'profile' %}"><i class="bi bi-person-gear"></i> Профиль</a></li>
                                        {% if user.is_authenticated and user.is_superuser %}
                                        <li><a class="dropdown-item" href="{% url 'admin:index' %}"><i class="bi bi-sliders"></i> Администрирование</a></li>
                                        {% endif %}
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item link-danger" href="{% url 'users:logout' %}"><i class="bi bi-box-arrow-right"></i> Выйти</a></li>
                                    </ul>
                                </div>
                            {% else %}
                                <a class="btn btn-outline-light me-2" href="{% url 'users:login' %}" role="button">Войти</a>
                                <a class="btn btn-success" href="{% url 'users:signup' %}" role="button">Зарегистрироваться</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</header>