BigHouzzz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('users.urls')),
    path('profile/', views.profile, name='profile'),
    path('cars/', include('cars.urls')),
    path('house/', include('flats.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:  # Если запущен режим отладки, то
    # Добавить пути для статических файлов STATIC и MEDIA
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    # Включить инструмент отладки Django Debug Toolbar
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.csrf_failure'

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('<int:car_id>/', views.car_detail, name='car_detail'),
    path('', views.cars_index, name='cars_index'),
]

cars/models.py
from django.db import models
from core.models import Colors
from users.models import User

class VehicleCategory(models.Model):
    """ Категория транспортного средства """
    name = models.CharField('Категория', max_length=100)
    icon = models.ImageField(
        'Путь до иконки',
        upload_to='img_category',
        blank=True,
        null=True
    )
    is_active = models.BooleanField(
        'Активный',
        default=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория ТС'
        verbose_name_plural = 'Категории ТС'


class VehicleBrand(models.Model):
    """ Марка транспортного средства """
    vehicle_brand = models.CharField('Марка ТС', max_length=100)

    def __str__(self):
        return self.vehicle_brand

    class Meta:
        verbose_name = 'Марка ТС'
        verbose_name_plural = 'Марка ТС'


class VehicleModel(models.Model):
    """ Модель транспортного средства """
    vehicle_model = models.CharField(max_length=255, verbose_name='Модель ТС')

    def __str__(self):
        return self.vehicle_model

    class Meta:
        verbose_name = 'Модель ТС'
        verbose_name_plural = 'Модель ТС'


class Vehicle(models.Model):
    """ Транспортное средство """
    regnum = models.CharField(
        'Регистрационный знак',
        max_length=10,
        db_index=True
    )
    is_alien = models.BooleanField(
        'Иностранный?',
        default=False
    )
    category = models.ForeignKey(
        VehicleCategory,
        verbose_name='Тип ТС',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )
    model = models.CharField('Модель', max_length=200)
    color = models.ForeignKey(
        Colors,
        verbose_name='Цвет кузова',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )
    driver = models.ForeignKey(
        User,
        verbose_name='Водитель',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )
    updated = models.DateTimeField(
        'Дата обновления',
        auto_now=True
    )
    is_active = models.BooleanField(
        'Активный',
        default=True
    )
    main_image = models.ImageField(
        'Основное изображение',
        upload_to='vehicles_images',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Транспортное средство'
        verbose_name_plural = 'Транспортные средства'
        ordering = ('regnum',)

    def __str__(self):
        return self.regnum

class Act(models.Model):
    """ Поведение """
    pass
    #
    # # CHOICES
    #
    # # DATABASE FIELDS
    # user = models.ForeignKey(
    #     User,
    #     verbose_name='Пользователь',
    #     on_delete=models.PROTECT,
    #     blank=True,
    #     null=True,
    # )
    # rating = models.CharField(
    #     'Оценка',
    #     max_length=1,
    #     choices=RATING_CHOICES,
    #     blank=True,
    # )
    # text = models.TextField(
    #     'Текст отзыва',
    #     max_length=250,
    #     blank=True,
    # )
    # is_active = models.BooleanField(
    #     'Активный',
    #     default=True
    # )
    # created = models.DateTimeField(
    #     'Дата создания',
    #     auto_now_add=True
    # )
    #
    # # META CLASS
    # class Meta:
    #     verbose_name = 'Отзыв'
    #     verbose_name_plural = 'Отзывы'
    #     ordering = ('created',)
    #
    # # TO STRING METHOD
    # # def __str__(self):
    # #    return self.id

cars/views.py
from django.shortcuts import render, get_object_or_404
from .models import Vehicle, VehicleCategory


def cars_index(request):
    """ Список транспортных средств """
    # Получение списка категорий транспортных средств
    list_cat = VehicleCategory.objects.filter(is_active=True).order_by('name')

    if request.method == "POST":
        selected_category = int(request.POST.get('category_filter'))
        if selected_category == 0:  # Не выбрана ни одна из категорий
            vehicles = Vehicle.objects.filter(is_active=True)
        else:
            vehicles = Vehicle.objects.filter(is_active=True,
                                              category=selected_category)
    else:  # Если это GET-запрос (впервые открывается страница)
        selected_category = 0
        vehicles = Vehicle.objects.filter(is_active=True)

    num_vehicles = vehicles.count()
    context = {
        'categories': list_cat,
        'selected_category': selected_category,
        'num_vehicles': num_vehicles,
        'vehicles': vehicles,
    }
    return render(request, 'cars/index.html', context)


def car_detail(request, car_id):
    """ Транспортное средство детально """
    vehicle = get_object_or_404(Vehicle, pk=car_id)
    context = {
        'vehicle': vehicle,
    }
    return render(request, 'cars/car_detail.html', context)

templates/cars/car_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Транспорт - подробно{% endblock %}
{% block content %}
<div class="container-fluid">
    <h1>Информация о транспортном средстве:</h1>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img src="{% if vehicle.main_image %} {{ vehicle.main_image.url }} {% else %} {% static 'vendor/img/vehicles/default_vehicle.jpeg' %} {% endif %}"
                     class="img-fluid rounded">
            </div>
            <div class="col-md-8">
                <table class="table table-hover">
                    <tbody>
                    <tr>
                        <th scope="row" class="table-primary text-end">Рег.
                            знак:
                        </th>
                        <td class="table-primary">{{ vehicle.regnum|upper }}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-end">Категория ТС:</th>
                        <td>{{ vehicle.category }}</td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-end">Модель:</th>
                        <td>{{ vehicle.model }}</td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-end">Цвет кузова:</th>
                        <td>{{ vehicle.color|default_if_none:"---" }}</td>
                    </tr>
                    </tbody>
                </table>

                {# Информация о водителе #}
                <h5>Информация о водителе:</h5>
                <table class="table table-hover">
                    <tbody>
                    <tr>
                        <th scope="row" class="text-end">Имя:</th>
                        <td>{{ vehicle.driver.last_name }} {{ vehicle.driver.first_name }} {{ vehicle.driver.patronymic_name }}</td>
                    </tr>
                    <tr>
                        <th scope="row" class="text-end">Телефон:</th>
                        <td>
                            <a href="tel:{{ vehicle.driver.phone_number }}">{{ vehicle.driver.phone_number|default_if_none:"---" }}</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/cars/car_index_filter.html
{# Filter #}
<form method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
        <select class="form-select" aria-label="Выбор типа ТС"
                name="category_filter" style="width:40%">
            <option value="0">Все категории ТС</option>
            {% for cat in categories %}
            <option value="{{ cat.id }}" {% if selected_category == cat.id %}
                    selected {% endif %}>{{ cat.name }}
            </option>
            {% endfor %}
        </select>
        <input type="submit" class="btn btn-success" value="Применить">
    </div>
</form>

templates/cars/index.html
{% extends "base.html" %}
{% block title %}Транспорт{% endblock %}
{% block content %}
<div class="container-fluid">
    <h1>Транспорт</h1>
    {# Filter #}
    {% include 'cars/car_index_filter.html' %}
    <table class="table table-sm table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Рег. знак</th>
            <th scope="col">Модель</th>
            <th scope="col">Цвет кузова</th>
            <th scope="col">Действие</th>
        </tr>
        </thead>
        <tbody>
        {% for vehicle in vehicles %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ vehicle.regnum|upper }}</td>
            <td>{{ vehicle.model }}</td>
            <td>{{ vehicle.color|default_if_none:"---" }}</td>
            <td><a class="btn btn-success"
                   href="{% url 'cars:car_detail' vehicle.id %}" role="button">Подробно</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}